### ISSUE TITLE
consider renaming repository.

### ISSUE THREAD

**Issue by danmarsden** [christos312/get_user_cohorts#3]
You may want to rename the repository here from "get_user_cohorts" to something that fits the "frankenstyle" naming convention that is familiar to moodle site admins using github - this would be:
"moodle-local_get_user_cohorts" - most moodle plugins hosted on github use this naming convention.

This is completely optional and will not block approval in the plugins db, so feel free to close as "won't fix" for whatever reason! :-)

**Comment by ghost** [comment]
Done
